library(DBI)
library(odbc)
library(writexl)
library(glue)
library(magrittr)
library(dplyr)
library(readxl)
library(conflicted)
library(dbplyr)
library(lubridate)
library(janitor)
library(readr)
library(Microsoft365R)
library(blastula)
library(janitor)

### --- CREACION REPORTE 10 X EMPRESA ---- ## CIERRE ##


## Leer foto ##

Foto_inicial <- read_excel("C:/Users/jjvt9593/OneDrive - Grupo Coomeva/Escritorio/Carpetas/Corrección R-10/Insumos/Junio/Foto_inicial.xlsx")


Connecion_SQL <- dbConnect( 
  odbc(),
  Driver = "Oracle in instantclient_21_3",
  DBQ = "bdcdpora23.intracoomeva.com.co:1575/CDPORA23", 
  SVC = "GRC", 
  encoding = "ISO-8859-1", 
  UID = "jjvt9593", 
  PWD = "KyCo_090625*")

## Coomeva Hoy ## 

Coomeva_hoy <- dbGetQuery(Connecion_SQL,glue_sql("SELECT ASO_IDENTIFICACION,
MAX(CASE WHEN FACT_NUMERO_CUOTAS_ATRASADAS >= 7 THEN 7 ELSE FACT_NUMERO_CUOTAS_ATRASADAS END) EDAD_CARTERA_HOY,
SUM(FAC.FACT_VALOR_CUOTA_MES) VALOR_CUOTA_MES_HOY,
SUM(FAC.FACT_VALOR_VENCIDO) VALOR_VENCIDO_HOY,
SUM(FAC.FACT_VALOR_CUOTA_MES + FAC.FACT_VALOR_VENCIDO) TOTAL_FACTURADO
FROM GRC.STG_GCC_FACTURACION FAC
LEFT OUTER JOIN GRC.GCC_CONCEPTO CON
ON FAC.CON_CODIGO = CON.CON_CODIGO
LEFT OUTER JOIN GRC.GCC_AGRUPACION EMP
ON CON.AGR_CODIGO = EMP.AGR_CODIGO
WHERE emp.age_codigo = 3
GROUP BY (FAC.ASO_IDENTIFICACION)"))

## MP Hoy ##

Mp_hoy <- dbGetQuery(Connecion_SQL,glue_sql(
  "SELECT ASO_IDENTIFICACION,
MAX(CASE WHEN FACT_NUMERO_CUOTAS_ATRASADAS >= 7 THEN 7 ELSE FACT_NUMERO_CUOTAS_ATRASADAS END) EDAD_CARTERA_HOY,
SUM(FAC.FACT_VALOR_CUOTA_MES) VALOR_CUOTA_MES_HOY,
SUM(FAC.FACT_VALOR_VENCIDO) VALOR_VENCIDO_HOY,
SUM(FAC.FACT_VALOR_CUOTA_MES + FAC.FACT_VALOR_VENCIDO) TOTAL_FACTURADO
FROM GRC.STG_GCC_FACTURACION FAC
LEFT OUTER JOIN GRC.GCC_CONCEPTO CON
ON FAC.CON_CODIGO = CON.CON_CODIGO
LEFT OUTER JOIN GRC.GCC_AGRUPACION EMP
ON CON.AGR_CODIGO = EMP.AGR_CODIGO
WHERE emp.age_codigo = 2 
AND FAC.CON_CODIGO NOT IN ('CEMR',
'01CEAB',
'01CEAD',
'01CEAG',
'01CEAM',
'01CEAP',
'01CEAS',
'01CEAT',
'01CEA9',
'01CEB',
'01CEB1',
'01CECA',
'01CECE',
'01CEC1',
'01CEEF',
'01CEE1',
'01CEE2',
'01CEFE',
'01CEFG',
'01CEFI',
'01CEFO',
'01CEGF',
'01CEIN',
'01CEM',
'01CEMA',
'01CEMB',
'01CEMC',
'01CEME',
'01CEMH',
'01CEMJ',
'01CEMO',
'01CEMS',
'01CEMX',
'01CEMZ',
'01CEM1',
'01CEM3',
'01CEM4',
'01CEM7',
'01CEM8',
'01CEOC',
'01CEPD',
'01CEPM',
'01CEPO',
'01CEPR',
'01CEPS',
'01CEP2',
'01CERP',
'01CETE',
'01CET9',
'01CEUS',
'01CEX0',
'01CEX1',
'01CEX3',
'01CE19',
'01CE2P',
'01CE23',
'01CPEM',
'01EVEM',
'04CEAB',
'04CEAD',
'04CEAG',
'04CEAM',
'04CEAP',
'04CEAS',
'04CEAT',
'04CEA9',
'04CEB',
'04CEB1',
'04CECA',
'04CECE',
'04CEC1',
'04CEEF',
'04CEE1',
'04CEE2',
'04CEFE',
'04CEFG',
'04CEFI',
'04CEFO',
'04CEGF',
'04CEIN',
'04CEM',
'04CEMA',
'04CEMB',
'04CEMC',
'04CEME',
'04CEMH',
'04CEMJ',
'04CEMO',
'04CEMS',
'04CEMX',
'04CEMZ',
'04CEM1',
'04CEM3',
'04CEM4',
'04CEM7',
'04CEM8',
'04CEOC',
'04CEPD',
'04CEPM',
'04CEPO',
'04CEPR',
'04CEPS',
'04CEP2',
'04CERP',
'04CETE',
'04CET9',
'04CEUS',
'04CEX0',
'04CEX1',
'04CEX3',
'04CE19',
'04CE2P',
'04CE23',
'04CPEM',
'04EVEM',
'07CEM',
'07CEMC',
'07CEMO',
'07CEMS',
'07CEMZ',
'07CEM1',
'07CEM3',
'07CEM4',
'07CEM7',
'07CEM8',
'08CEM',
'08CEMC',
'08CEMJ',
'08CEMO',
'08CEMS',
'08CEMZ',
'08CEM1',
'08CEM3',
'08CEM4',
'08CEM7',
'08CEM8',
'09CEAG',
'09CEAP',
'09CEAS',
'09CEAT',
'09CEFE',
'09CEFG',
'09CEFO',
'09CEGF',
'09CEM',
'09CEMC',
'09CEMH',
'09CEMO',
'09CEMZ',
'09CEM1',
'09CEM3',
'09CEM4',
'09CEM7',
'09CEM8',
'09CEPD',
'09CEPM',
'09CEPO',
'09CEPR',
'09CEPS',
'09CEP2',
'09CERP',
'09CEX3',
'09CE2P',
'01CEMQ',
'04CEMQ',
'01CE50',
'04CE50',
'01PACE',
'04PACE',
'01TACE',
'04TACE',
'01CUE3',
'04CUE3',
'01CUE6',
'04CUE6',
'01CUE9',
'04CUE9',
'01CU12',
'04CU12',
'01CU23',
'04CU23',
'01CU26',
'04CU26',
'01CU29',
'04CU29',
'01CU22',
'04CU22',
'01CTL3',
'04CTL3',
'01CTL6',
'04CTL6',
'01CTL9',
'04CTL9',
'01CT12',
'04CT12',
'01CT23',
'04CT23',
'01CT26',
'04CT26',
'01CT29',
'04CT29',
'01CT22',
'04CT22',
'01FULL',
'04FULL')
GROUP BY (FAC.ASO_IDENTIFICACION);"))

## CEM Hoy ##

CEM_hoy <- dbGetQuery(Connecion_SQL,glue_sql(
  "SELECT ASO_IDENTIFICACION,
MAX(CASE WHEN FACT_NUMERO_CUOTAS_ATRASADAS >= 7 THEN 7 ELSE FACT_NUMERO_CUOTAS_ATRASADAS END) EDAD_CARTERA_HOY,
SUM(FAC.FACT_VALOR_CUOTA_MES) VALOR_CUOTA_MES_HOY,
SUM(FAC.FACT_VALOR_VENCIDO) VALOR_VENCIDO_HOY,
SUM(FAC.FACT_VALOR_CUOTA_MES + FAC.FACT_VALOR_VENCIDO) TOTAL_FACTURADO
FROM GRC.STG_GCC_FACTURACION FAC
LEFT OUTER JOIN GRC.GCC_CONCEPTO CON
ON FAC.CON_CODIGO = CON.CON_CODIGO
LEFT OUTER JOIN GRC.GCC_AGRUPACION EMP
ON CON.AGR_CODIGO = EMP.AGR_CODIGO
WHERE emp.age_codigo = 2 
AND FAC.CON_CODIGO IN ('CEMR',
'01CEAB',
'01CEAD',
'01CEAG',
'01CEAM',
'01CEAP',
'01CEAS',
'01CEAT',
'01CEA9',
'01CEB',
'01CEB1',
'01CECA',
'01CECE',
'01CEC1',
'01CEEF',
'01CEE1',
'01CEE2',
'01CEFE',
'01CEFG',
'01CEFI',
'01CEFO',
'01CEGF',
'01CEIN',
'01CEM',
'01CEMA',
'01CEMB',
'01CEMC',
'01CEME',
'01CEMH',
'01CEMJ',
'01CEMO',
'01CEMS',
'01CEMX',
'01CEMZ',
'01CEM1',
'01CEM3',
'01CEM4',
'01CEM7',
'01CEM8',
'01CEOC',
'01CEPD',
'01CEPM',
'01CEPO',
'01CEPR',
'01CEPS',
'01CEP2',
'01CERP',
'01CETE',
'01CET9',
'01CEUS',
'01CEX0',
'01CEX1',
'01CEX3',
'01CE19',
'01CE2P',
'01CE23',
'01CPEM',
'01EVEM',
'04CEAB',
'04CEAD',
'04CEAG',
'04CEAM',
'04CEAP',
'04CEAS',
'04CEAT',
'04CEA9',
'04CEB',
'04CEB1',
'04CECA',
'04CECE',
'04CEC1',
'04CEEF',
'04CEE1',
'04CEE2',
'04CEFE',
'04CEFG',
'04CEFI',
'04CEFO',
'04CEGF',
'04CEIN',
'04CEM',
'04CEMA',
'04CEMB',
'04CEMC',
'04CEME',
'04CEMH',
'04CEMJ',
'04CEMO',
'04CEMS',
'04CEMX',
'04CEMZ',
'04CEM1',
'04CEM3',
'04CEM4',
'04CEM7',
'04CEM8',
'04CEOC',
'04CEPD',
'04CEPM',
'04CEPO',
'04CEPR',
'04CEPS',
'04CEP2',
'04CERP',
'04CETE',
'04CET9',
'04CEUS',
'04CEX0',
'04CEX1',
'04CEX3',
'04CE19',
'04CE2P',
'04CE23',
'04CPEM',
'04EVEM',
'07CEM',
'07CEMC',
'07CEMO',
'07CEMS',
'07CEMZ',
'07CEM1',
'07CEM3',
'07CEM4',
'07CEM7',
'07CEM8',
'08CEM',
'08CEMC',
'08CEMJ',
'08CEMO',
'08CEMS',
'08CEMZ',
'08CEM1',
'08CEM3',
'08CEM4',
'08CEM7',
'08CEM8',
'09CEAG',
'09CEAP',
'09CEAS',
'09CEAT',
'09CEFE',
'09CEFG',
'09CEFO',
'09CEGF',
'09CEM',
'09CEMC',
'09CEMH',
'09CEMO',
'09CEMZ',
'09CEM1',
'09CEM3',
'09CEM4',
'09CEM7',
'09CEM8',
'09CEPD',
'09CEPM',
'09CEPO',
'09CEPR',
'09CEPS',
'09CEP2',
'09CERP',
'09CEX3',
'09CE2P',
'01CEMQ',
'04CEMQ',
'01CE50',
'04CE50',
'01PACE',
'04PACE',
'01TACE',
'04TACE',
'01CUE3',
'04CUE3',
'01CUE6',
'04CUE6',
'01CUE9',
'04CUE9',
'01CU12',
'04CU12',
'01CU23',
'04CU23',
'01CU26',
'04CU26',
'01CU29',
'04CU29',
'01CU22',
'04CU22',
'01CTL3',
'04CTL3',
'01CTL6',
'04CTL6',
'01CTL9',
'04CTL9',
'01CT12',
'04CT12',
'01CT23',
'04CT23',
'01CT26',
'04CT26',
'01CT29',
'04CT29',
'01CT22',
'04CT22',
'01FULL',
'04FULL')
GROUP BY (FAC.ASO_IDENTIFICACION);"))

## Seguros Hoy ##

Seguros_hoy <- dbGetQuery(Connecion_SQL,glue_sql("SELECT ASO_IDENTIFICACION,
                                                 MAX(CASE WHEN FACT_NUMERO_CUOTAS_ATRASADAS >= 7 THEN 7 ELSE FACT_NUMERO_CUOTAS_ATRASADAS END) EDAD_CARTERA_HOY,
                                                 SUM(FACT_VALOR_CUOTA_MES) VALOR_CUOTA_MES_HOY,
                                                 SUM(FACT_VALOR_VENCIDO) VALOR_VENCIDO_HOY,
                                                 SUM(FACT_VALOR_CUOTA_MES + FACT_VALOR_VENCIDO) TOTAL_FACTURADO
                                                 FROM GRC.STG_GCC_FACTURACION
                                                 WHERE CON_CODIGO IN ('SEGAUTOC',
                                                                      'DESEMPLE',
                                                                      'PYMEBANC',
                                                                      'SEG ROTU',
                                                                      'SEGSOAT',
                                                                      'ASISTAFA',
                                                                      'VIDACOOM',
                                                                      'SEG AUTO',
                                                                      'HOGMASBA',
                                                                      'SEGINCBA',
                                                                      'INCCLIBA',
                                                                      'SEGAUTMD',
                                                                      'SEGAUTBO',
                                                                      'AUTOAMPB',
                                                                      'AUT PESA',
                                                                      'BOLBILLE',
                                                                      'CLINIMAS',
                                                                      'CLINIMA2',
                                                                      'SEG CUBR',
                                                                      'EVCRICOO',
                                                                      'EVCRIMP',
                                                                      'ECMPFTF',
                                                                      'FLE.HOG+',
                                                                      'SEG HOGA',
                                                                      'HOMEEJEC',
                                                                      'SEG INCE',
                                                                      'AUTLIV',
                                                                      'AUTLIB',
                                                                      'Seg+Prot',
                                                                      'SEG MOTO',
                                                                      'SEGMASCO',
                                                                      'SEGMOCHI',
                                                                      'PAGPROTN',
                                                                      'PAGO SEG',
                                                                      'PENPRVOL',
                                                                      'SEG PLAN',
                                                                      'VIDASOLI',
                                                                      'SEG.A.EJ',
                                                                      'SEG GAP',
                                                                      'AUTOLIV3',
                                                                      'PROT.EDU',
                                                                      'SEG PAGP',
                                                                      'PLAN100L',
                                                                      'SEGAUTOS',
                                                                      'SEGMYCAR',
                                                                      'MOVIBIC',
                                                                      'AUTOLICF',
                                                                      'AUTOLIVN',
                                                                      'LIVESECF',
                                                                      'LIVESEN',
                                                                      'MASPRONU',
                                                                      'VIDAEG',
                                                                      'VIDARENH',
                                                                      'VIDA',
                                                                      'LIVFULL',
                                                                      'LIVFULCF',
                                                                      'INCORIGI',
                                                                      'INCORICF',
                                                                      'RENTA HG',
                                                                      'RENTHONU',
                                                                      'SEG CIVI',
                                                                      'S.RC.Exc',
                                                                      'SEG RESC',
                                                                      'S.RC.CLI',
                                                                      'RCMEDLIV',
                                                                      'ORIVIVI',
                                                                      'RC MED',
                                                                      'ARCEPT',
                                                                      'ARCEBA',
                                                                      'RUNT',
                                                                      'SEGRUNT',
                                                                      'EQELECBA',
                                                                      'TAXIBANC',
                                                                      'SEG ACCI',
                                                                      'SEG ELEC',
                                                                      'SEG.SOAT',
                                                                      'SEG RENT',
                                                                      'SEG.VEH.',
                                                                      'SEGVICBA',
                                                                      'SEGVIGC',
                                                                      'SEGMOTBA',
                                                                      'SEGVEHBA',
                                                                      'SEGVEHCB',
                                                                      'VEHPESBA',
                                                                      'SEG SUST',
                                                                      'SEG PYME',
                                                                      'SEGMPSTO',
                                                                      'CREDASOC',
                                                                      'SEGVIDVA',
                                                                      'SEGVGFS',
                                                                      'SEG TAMP',
                                                                      'SEG.TAXI',
                                                                      'TOHOMLIF',
                                                                      'TOHOMLIV',
                                                                      'TMKBSEG',
                                                                      'VGORIGCF')
                                                 GROUP BY(ASO_IDENTIFICACION)"))

## LEER SEGUIMIENTO - R10 ##

Ruta <- ruta_carpeta <- "C:/Users/jjvt9593/OneDrive - Grupo Coomeva/Escritorio/Carpetas/Corrección R-10/Resultado/Seguimientos"

archivos_con_fechas <- file.info(list.files(path = ruta_carpeta, full.names = TRUE))

archivos_excel <- archivos_con_fechas[grep("\\.xlsx$", rownames(archivos_con_fechas), ignore.case = TRUE), ]

ultimo_archivo <- rownames(archivos_excel)[which.max(archivos_excel$mtime)]

r10 <- read_excel(ultimo_archivo)

r10 <- r10 %>% mutate(`CEDULA ASOCIADO` = as.double(`CEDULA ASOCIADO`))

 ## ---- Coomeva ----

# Valores Iniciales Coomeva ##

r10 <- r10 %>% left_join(Foto_inicial %>% select(ASO_IDENTIFICACION,Validacion_Coomeva,Edad_Inicial_Coomeva,Valor_Vencido_Periodo_Coomeva,Total_Fac_Coomeva), by = c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))

## Edad y Vencido Hoy Coomeva ##

r10 <- r10 %>% left_join(Coomeva_hoy %>%  select(ASO_IDENTIFICACION,EDAD_CARTERA_HOY,VALOR_VENCIDO_HOY), by=c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))

r10 <- r10 %>% rename(EDAD_HOY_COOMEVA = EDAD_CARTERA_HOY)

r10 <- r10 %>% rename(VALOR_VENCIDO_COOMEVA_HOY = VALOR_VENCIDO_HOY)

r10 <- r10 %>% mutate(VALOR_VENCIDO_COOMEVA_HOY = if_else(is.na(VALOR_VENCIDO_COOMEVA_HOY),0,VALOR_VENCIDO_COOMEVA_HOY))

## Pagos Coomeva ## 

Pagos_Coomeva <- dbGetQuery(Connecion_SQL,glue_sql("SELECT REC.ASO_IDENTIFICACION_ASOCIADO, 
       SUM(REC.HRCD_VALOR_RECAUDO) AS VALOR_RECAUDO_TOTAL,
       SUM(CASE 
               WHEN REC.HRCD_PERIODO_FACTURACION < 202506 
              THEN REC.HRCD_VALOR_RECAUDO 
               ELSE 0 
           END) AS VALOR_RECAUDO_VENCIDO
    FROM GRC.GCC_HISTORIA_RECAUDO REC
    LEFT OUTER JOIN GRC.GCC_CONCEPTO CON
    ON REC.CON_CODIGO = CON.CON_CODIGO
    LEFT OUTER JOIN GRC.GCC_AGRUPACION EMP
    ON CON.AGR_CODIGO = EMP.AGR_CODIGO
    WHERE REC.HRCD_NRO_TRANSACCION NOT IN ('71','52','51')
      AND REC.HRCD_FECHA_RECAUDO BETWEEN TO_DATE('01/06/2025', 'DD/MM/YYYY') AND TO_DATE('30/06/2025', 'DD/MM/YYYY')
      AND EMP.AGE_CODIGO = 3
      GROUP BY REC.ASO_IDENTIFICACION_ASOCIADO;"))

r10 <- r10 %>% left_join(Pagos_Coomeva %>%  select(ASO_IDENTIFICACION_ASOCIADO,VALOR_RECAUDO_TOTAL,VALOR_RECAUDO_VENCIDO), by=c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION_ASOCIADO"))

r10 <- r10 %>% rename(RECAUDO_TOTAL_COOMEVA = VALOR_RECAUDO_TOTAL)

r10 <- r10 %>% rename(RECAUDO_VENCIDO_COOMEVA = VALOR_RECAUDO_VENCIDO)


## Valores recaudos vencidos para mora 0 ##

Pagos_Mora_1_Coomeva <- dbGetQuery(Connecion_SQL,glue_sql("SELECT 
                                                   ASO_IDENTIFICACION,
                                                   SUM(HFR_VALOR_RCDO_VENC_FIN + HFR_VALOR_RCDO_VENC_MULT) AS VALOR_RECAUDO_VENCIDO
                                                   FROM GRC.GCC_HIST_FACT_RECAUDO
                                                   WHERE HFR_PERIODO_FACT = '202507'
                                                   AND AGE_NOMBRE = 'COOMEVA'
                                                   GROUP BY ASO_IDENTIFICACION;"))

r10 <- r10 %>% left_join(Pagos_Mora_1_Coomeva, by = c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))


r10 <- r10 %>% mutate(RECAUDO_VENCIDO_COOMEVA = if_else(Edad_Inicial_Coomeva == 0,VALOR_RECAUDO_VENCIDO,RECAUDO_VENCIDO_COOMEVA))

r10 <- r10 %>% select(-VALOR_RECAUDO_VENCIDO)


    
## --- Medicina Prepagada --- ##

### Valores iniciales MP ###

r10 <- r10 %>% left_join(Foto_inicial %>% select(ASO_IDENTIFICACION,Validacion_Mp,Edad_Inicial_MP,Valor_Vencido_Periodo_MP,Total_Fac_MP), by = c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))


### Valores Hoy MP ### 

r10 <- r10 %>% left_join(Mp_hoy %>%  select(ASO_IDENTIFICACION,EDAD_CARTERA_HOY,VALOR_VENCIDO_HOY), by=c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))

r10 <- r10 %>% rename(EDAD_HOY_MP = EDAD_CARTERA_HOY)

r10 <- r10 %>% rename(VALOR_VENCIDO_MP_HOY = VALOR_VENCIDO_HOY)

r10 <- r10 %>% mutate(VALOR_VENCIDO_MP_HOY = if_else(is.na(VALOR_VENCIDO_MP_HOY),0,VALOR_VENCIDO_MP_HOY))


## PAGOS MP ## 

Pagos_MP <- dbGetQuery(Connecion_SQL,glue_sql(
"SELECT REC.ASO_IDENTIFICACION_ASOCIADO, 
       SUM(REC.HRCD_VALOR_RECAUDO) AS VALOR_RECAUDO_TOTAL,
       SUM(CASE 
               WHEN REC.HRCD_PERIODO_FACTURACION < 202506
              THEN REC.HRCD_VALOR_RECAUDO 
               ELSE 0 
           END) AS VALOR_RECAUDO_VENCIDO
    FROM GRC.GCC_HISTORIA_RECAUDO REC
    LEFT OUTER JOIN GRC.GCC_CONCEPTO CON
    ON REC.CON_CODIGO = CON.CON_CODIGO
    LEFT OUTER JOIN GRC.GCC_AGRUPACION EMP
    ON CON.AGR_CODIGO = EMP.AGR_CODIGO
    WHERE REC.HRCD_NRO_TRANSACCION NOT IN ('71','52','51')
      AND REC.HRCD_FECHA_RECAUDO BETWEEN TO_DATE('01/06/2025', 'DD/MM/YYYY') AND TO_DATE('30/06/2025', 'DD/MM/YYYY')
      AND EMP.AGE_CODIGO = 2
AND REC.CON_CODIGO NOT IN ('CEMR',
'01CEAB',
'01CEAD',
'01CEAG',
'01CEAM',
'01CEAP',
'01CEAS',
'01CEAT',
'01CEA9',
'01CEB',
'01CEB1',
'01CECA',
'01CECE',
'01CEC1',
'01CEEF',
'01CEE1',
'01CEE2',
'01CEFE',
'01CEFG',
'01CEFI',
'01CEFO',
'01CEGF',
'01CEIN',
'01CEM',
'01CEMA',
'01CEMB',
'01CEMC',
'01CEME',
'01CEMH',
'01CEMJ',
'01CEMO',
'01CEMS',
'01CEMX',
'01CEMZ',
'01CEM1',
'01CEM3',
'01CEM4',
'01CEM7',
'01CEM8',
'01CEOC',
'01CEPD',
'01CEPM',
'01CEPO',
'01CEPR',
'01CEPS',
'01CEP2',
'01CERP',
'01CETE',
'01CET9',
'01CEUS',
'01CEX0',
'01CEX1',
'01CEX3',
'01CE19',
'01CE2P',
'01CE23',
'01CPEM',
'01EVEM',
'04CEAB',
'04CEAD',
'04CEAG',
'04CEAM',
'04CEAP',
'04CEAS',
'04CEAT',
'04CEA9',
'04CEB',
'04CEB1',
'04CECA',
'04CECE',
'04CEC1',
'04CEEF',
'04CEE1',
'04CEE2',
'04CEFE',
'04CEFG',
'04CEFI',
'04CEFO',
'04CEGF',
'04CEIN',
'04CEM',
'04CEMA',
'04CEMB',
'04CEMC',
'04CEME',
'04CEMH',
'04CEMJ',
'04CEMO',
'04CEMS',
'04CEMX',
'04CEMZ',
'04CEM1',
'04CEM3',
'04CEM4',
'04CEM7',
'04CEM8',
'04CEOC',
'04CEPD',
'04CEPM',
'04CEPO',
'04CEPR',
'04CEPS',
'04CEP2',
'04CERP',
'04CETE',
'04CET9',
'04CEUS',
'04CEX0',
'04CEX1',
'04CEX3',
'04CE19',
'04CE2P',
'04CE23',
'04CPEM',
'04EVEM',
'07CEM',
'07CEMC',
'07CEMO',
'07CEMS',
'07CEMZ',
'07CEM1',
'07CEM3',
'07CEM4',
'07CEM7',
'07CEM8',
'08CEM',
'08CEMC',
'08CEMJ',
'08CEMO',
'08CEMS',
'08CEMZ',
'08CEM1',
'08CEM3',
'08CEM4',
'08CEM7',
'08CEM8',
'09CEAG',
'09CEAP',
'09CEAS',
'09CEAT',
'09CEFE',
'09CEFG',
'09CEFO',
'09CEGF',
'09CEM',
'09CEMC',
'09CEMH',
'09CEMO',
'09CEMZ',
'09CEM1',
'09CEM3',
'09CEM4',
'09CEM7',
'09CEM8',
'09CEPD',
'09CEPM',
'09CEPO',
'09CEPR',
'09CEPS',
'09CEP2',
'09CERP',
'09CEX3',
'09CE2P',
'01CEMQ',
'04CEMQ',
'01CE50',
'04CE50',
'01PACE',
'04PACE',
'01TACE',
'04TACE',
'01CUE3',
'04CUE3',
'01CUE6',
'04CUE6',
'01CUE9',
'04CUE9',
'01CU12',
'04CU12',
'01CU23',
'04CU23',
'01CU26',
'04CU26',
'01CU29',
'04CU29',
'01CU22',
'04CU22',
'01CTL3',
'04CTL3',
'01CTL6',
'04CTL6',
'01CTL9',
'04CTL9',
'01CT12',
'04CT12',
'01CT23',
'04CT23',
'01CT26',
'04CT26',
'01CT29',
'04CT29',
'01CT22',
'04CT22',
'01FULL',
'04FULL')
GROUP BY REC.ASO_IDENTIFICACION_ASOCIADO;"))


r10 <- r10 %>% left_join(Pagos_MP %>%  select(ASO_IDENTIFICACION_ASOCIADO,VALOR_RECAUDO_TOTAL,VALOR_RECAUDO_VENCIDO), by=c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION_ASOCIADO"))

r10 <- r10 %>% rename(RECAUDO_TOTAL_mp = VALOR_RECAUDO_TOTAL)

r10 <- r10 %>% rename(RECAUDO_VENCIDO_mp = VALOR_RECAUDO_VENCIDO)

## Valores recaudos vencidos para mora 0 ##

Pagos_Mora_1_MP <- dbGetQuery(Connecion_SQL,glue_sql("SELECT 
                                                   ASO_IDENTIFICACION,
                                                   SUM(HFR_VALOR_RCDO_VENC_FIN + HFR_VALOR_RCDO_VENC_MULT) AS VALOR_RECAUDO_VENCIDO
                                                   FROM GRC.GCC_HIST_FACT_RECAUDO
                                                   WHERE HFR_PERIODO_FACT = '202507'
                                                   AND AGE_NOMBRE = 'MEDICINA PREPAGADA'
                                                   AND CON_CODIGO NOT IN ('CEMR',
'01CEAB',
'01CEAD',
'01CEAG',
'01CEAM',
'01CEAP',
'01CEAS',
'01CEAT',
'01CEA9',
'01CEB',
'01CEB1',
'01CECA',
'01CECE',
'01CEC1',
'01CEEF',
'01CEE1',
'01CEE2',
'01CEFE',
'01CEFG',
'01CEFI',
'01CEFO',
'01CEGF',
'01CEIN',
'01CEM',
'01CEMA',
'01CEMB',
'01CEMC',
'01CEME',
'01CEMH',
'01CEMJ',
'01CEMO',
'01CEMS',
'01CEMX',
'01CEMZ',
'01CEM1',
'01CEM3',
'01CEM4',
'01CEM7',
'01CEM8',
'01CEOC',
'01CEPD',
'01CEPM',
'01CEPO',
'01CEPR',
'01CEPS',
'01CEP2',
'01CERP',
'01CETE',
'01CET9',
'01CEUS',
'01CEX0',
'01CEX1',
'01CEX3',
'01CE19',
'01CE2P',
'01CE23',
'01CPEM',
'01EVEM',
'04CEAB',
'04CEAD',
'04CEAG',
'04CEAM',
'04CEAP',
'04CEAS',
'04CEAT',
'04CEA9',
'04CEB',
'04CEB1',
'04CECA',
'04CECE',
'04CEC1',
'04CEEF',
'04CEE1',
'04CEE2',
'04CEFE',
'04CEFG',
'04CEFI',
'04CEFO',
'04CEGF',
'04CEIN',
'04CEM',
'04CEMA',
'04CEMB',
'04CEMC',
'04CEME',
'04CEMH',
'04CEMJ',
'04CEMO',
'04CEMS',
'04CEMX',
'04CEMZ',
'04CEM1',
'04CEM3',
'04CEM4',
'04CEM7',
'04CEM8',
'04CEOC',
'04CEPD',
'04CEPM',
'04CEPO',
'04CEPR',
'04CEPS',
'04CEP2',
'04CERP',
'04CETE',
'04CET9',
'04CEUS',
'04CEX0',
'04CEX1',
'04CEX3',
'04CE19',
'04CE2P',
'04CE23',
'04CPEM',
'04EVEM',
'07CEM',
'07CEMC',
'07CEMO',
'07CEMS',
'07CEMZ',
'07CEM1',
'07CEM3',
'07CEM4',
'07CEM7',
'07CEM8',
'08CEM',
'08CEMC',
'08CEMJ',
'08CEMO',
'08CEMS',
'08CEMZ',
'08CEM1',
'08CEM3',
'08CEM4',
'08CEM7',
'08CEM8',
'09CEAG',
'09CEAP',
'09CEAS',
'09CEAT',
'09CEFE',
'09CEFG',
'09CEFO',
'09CEGF',
'09CEM',
'09CEMC',
'09CEMH',
'09CEMO',
'09CEMZ',
'09CEM1',
'09CEM3',
'09CEM4',
'09CEM7',
'09CEM8',
'09CEPD',
'09CEPM',
'09CEPO',
'09CEPR',
'09CEPS',
'09CEP2',
'09CERP',
'09CEX3',
'09CE2P',
'01CEMQ',
'04CEMQ',
'01CE50',
'04CE50',
'01PACE',
'04PACE',
'01TACE',
'04TACE',
'01CUE3',
'04CUE3',
'01CUE6',
'04CUE6',
'01CUE9',
'04CUE9',
'01CU12',
'04CU12',
'01CU23',
'04CU23',
'01CU26',
'04CU26',
'01CU29',
'04CU29',
'01CU22',
'04CU22',
'01CTL3',
'04CTL3',
'01CTL6',
'04CTL6',
'01CTL9',
'04CTL9',
'01CT12',
'04CT12',
'01CT23',
'04CT23',
'01CT26',
'04CT26',
'01CT29',
'04CT29',
'01CT22',
'04CT22',
'01FULL',
'04FULL') 
GROUP BY ASO_IDENTIFICACION;"))

r10 <- r10 %>% left_join(Pagos_Mora_1_MP, by = c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))


r10 <- r10 %>% mutate(RECAUDO_VENCIDO_mp = if_else(Edad_Inicial_MP == 0 & Valor_Vencido_Periodo_MP > 0,VALOR_RECAUDO_VENCIDO,RECAUDO_VENCIDO_mp))

r10 <- r10 %>% select(-VALOR_RECAUDO_VENCIDO)

## CEM ##

## VALORES INICIALES CEM ## 

r10 <- r10 %>% left_join(Foto_inicial %>% select(ASO_IDENTIFICACION,Validacion_CEM,Edad_Inicial_CEM,Valor_Vencido_Periodo_CEM,Total_Fac_CEM), by = c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))


## VALORES HOY CEM ##

r10 <- r10 %>% left_join(CEM_hoy %>%  select(ASO_IDENTIFICACION,EDAD_CARTERA_HOY,VALOR_VENCIDO_HOY), by=c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))

r10 <- r10 %>% rename(EDAD_HOY_CEM = EDAD_CARTERA_HOY)

r10 <- r10 %>% rename(VALOR_VENCIDO_CEM_HOY = VALOR_VENCIDO_HOY)

r10 <- r10 %>% mutate(VALOR_VENCIDO_CEM_HOY = if_else(is.na(VALOR_VENCIDO_CEM_HOY),0,VALOR_VENCIDO_CEM_HOY))

## PAGOS CEM ## 

Pagos_CEM <- dbGetQuery(Connecion_SQL,glue_sql(
  "SELECT 
REC.ASO_IDENTIFICACION_ASOCIADO, 
SUM(REC.HRCD_VALOR_RECAUDO) AS VALOR_RECAUDO_TOTAL,
SUM(CASE 
      WHEN REC.HRCD_PERIODO_FACTURACION < 202506
      THEN REC.HRCD_VALOR_RECAUDO 
      ELSE 0 
      END) AS VALOR_RECAUDO_VENCIDO
      FROM GRC.GCC_HISTORIA_RECAUDO REC
      LEFT OUTER JOIN GRC.GCC_CONCEPTO CON ON REC.CON_CODIGO = CON.CON_CODIGO
      WHERE 
      REC.HRCD_NRO_TRANSACCION NOT IN ('71','52','51')
      AND REC.HRCD_FECHA_RECAUDO BETWEEN TO_DATE('01/06/2025', 'DD/MM/YYYY') AND TO_DATE('30/06/2025', 'DD/MM/YYYY')
AND REC.CON_CODIGO IN ('CEMR',
'01CEAB',
'01CEAD',
'01CEAG',
'01CEAM',
'01CEAP',
'01CEAS',
'01CEAT',
'01CEA9',
'01CEB',
'01CEB1',
'01CECA',
'01CECE',
'01CEC1',
'01CEEF',
'01CEE1',
'01CEE2',
'01CEFE',
'01CEFG',
'01CEFI',
'01CEFO',
'01CEGF',
'01CEIN',
'01CEM',
'01CEMA',
'01CEMB',
'01CEMC',
'01CEME',
'01CEMH',
'01CEMJ',
'01CEMO',
'01CEMS',
'01CEMX',
'01CEMZ',
'01CEM1',
'01CEM3',
'01CEM4',
'01CEM7',
'01CEM8',
'01CEOC',
'01CEPD',
'01CEPM',
'01CEPO',
'01CEPR',
'01CEPS',
'01CEP2',
'01CERP',
'01CETE',
'01CET9',
'01CEUS',
'01CEX0',
'01CEX1',
'01CEX3',
'01CE19',
'01CE2P',
'01CE23',
'01CPEM',
'01EVEM',
'04CEAB',
'04CEAD',
'04CEAG',
'04CEAM',
'04CEAP',
'04CEAS',
'04CEAT',
'04CEA9',
'04CEB',
'04CEB1',
'04CECA',
'04CECE',
'04CEC1',
'04CEEF',
'04CEE1',
'04CEE2',
'04CEFE',
'04CEFG',
'04CEFI',
'04CEFO',
'04CEGF',
'04CEIN',
'04CEM',
'04CEMA',
'04CEMB',
'04CEMC',
'04CEME',
'04CEMH',
'04CEMJ',
'04CEMO',
'04CEMS',
'04CEMX',
'04CEMZ',
'04CEM1',
'04CEM3',
'04CEM4',
'04CEM7',
'04CEM8',
'04CEOC',
'04CEPD',
'04CEPM',
'04CEPO',
'04CEPR',
'04CEPS',
'04CEP2',
'04CERP',
'04CETE',
'04CET9',
'04CEUS',
'04CEX0',
'04CEX1',
'04CEX3',
'04CE19',
'04CE2P',
'04CE23',
'04CPEM',
'04EVEM',
'07CEM',
'07CEMC',
'07CEMO',
'07CEMS',
'07CEMZ',
'07CEM1',
'07CEM3',
'07CEM4',
'07CEM7',
'07CEM8',
'08CEM',
'08CEMC',
'08CEMJ',
'08CEMO',
'08CEMS',
'08CEMZ',
'08CEM1',
'08CEM3',
'08CEM4',
'08CEM7',
'08CEM8',
'09CEAG',
'09CEAP',
'09CEAS',
'09CEAT',
'09CEFE',
'09CEFG',
'09CEFO',
'09CEGF',
'09CEM',
'09CEMC',
'09CEMH',
'09CEMO',
'09CEMZ',
'09CEM1',
'09CEM3',
'09CEM4',
'09CEM7',
'09CEM8',
'09CEPD',
'09CEPM',
'09CEPO',
'09CEPR',
'09CEPS',
'09CEP2',
'09CERP',
'09CEX3',
'09CE2P',
'01CEMQ',
'04CEMQ',
'01CE50',
'04CE50',
'01PACE',
'04PACE',
'01TACE',
'04TACE',
'01CUE3',
'04CUE3',
'01CUE6',
'04CUE6',
'01CUE9',
'04CUE9',
'01CU12',
'04CU12',
'01CU23',
'04CU23',
'01CU26',
'04CU26',
'01CU29',
'04CU29',
'01CU22',
'04CU22',
'01CTL3',
'04CTL3',
'01CTL6',
'04CTL6',
'01CTL9',
'04CTL9',
'01CT12',
'04CT12',
'01CT23',
'04CT23',
'01CT26',
'04CT26',
'01CT29',
'04CT29',
'01CT22',
'04CT22',
'01FULL',
'04FULL')
GROUP BY REC.ASO_IDENTIFICACION_ASOCIADO;"))

r10 <- r10 %>% left_join(Pagos_CEM %>%  select(ASO_IDENTIFICACION_ASOCIADO,VALOR_RECAUDO_TOTAL,VALOR_RECAUDO_VENCIDO), by=c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION_ASOCIADO"))

r10 <- r10 %>% rename(RECAUDO_TOTAL_CEM = VALOR_RECAUDO_TOTAL)

r10 <- r10 %>% rename(RECAUDO_VENCIDO_CEM = VALOR_RECAUDO_VENCIDO)

## Recaudo Vencido mora 1 ##
Pagos_Mora_1_CEM <- dbGetQuery(Connecion_SQL,glue_sql("SELECT 
                                                   ASO_IDENTIFICACION,
                                                   SUM(HFR_VALOR_RCDO_VENC_FIN + HFR_VALOR_RCDO_VENC_MULT) AS VALOR_RECAUDO_VENCIDO
                                                   FROM GRC.GCC_HIST_FACT_RECAUDO
                                                   WHERE HFR_PERIODO_FACT = '202507'
                                                   AND CON_CODIGO IN ('CEMR',
'01CEAB',
'01CEAD',
'01CEAG',
'01CEAM',
'01CEAP',
'01CEAS',
'01CEAT',
'01CEA9',
'01CEB',
'01CEB1',
'01CECA',
'01CECE',
'01CEC1',
'01CEEF',
'01CEE1',
'01CEE2',
'01CEFE',
'01CEFG',
'01CEFI',
'01CEFO',
'01CEGF',
'01CEIN',
'01CEM',
'01CEMA',
'01CEMB',
'01CEMC',
'01CEME',
'01CEMH',
'01CEMJ',
'01CEMO',
'01CEMS',
'01CEMX',
'01CEMZ',
'01CEM1',
'01CEM3',
'01CEM4',
'01CEM7',
'01CEM8',
'01CEOC',
'01CEPD',
'01CEPM',
'01CEPO',
'01CEPR',
'01CEPS',
'01CEP2',
'01CERP',
'01CETE',
'01CET9',
'01CEUS',
'01CEX0',
'01CEX1',
'01CEX3',
'01CE19',
'01CE2P',
'01CE23',
'01CPEM',
'01EVEM',
'04CEAB',
'04CEAD',
'04CEAG',
'04CEAM',
'04CEAP',
'04CEAS',
'04CEAT',
'04CEA9',
'04CEB',
'04CEB1',
'04CECA',
'04CECE',
'04CEC1',
'04CEEF',
'04CEE1',
'04CEE2',
'04CEFE',
'04CEFG',
'04CEFI',
'04CEFO',
'04CEGF',
'04CEIN',
'04CEM',
'04CEMA',
'04CEMB',
'04CEMC',
'04CEME',
'04CEMH',
'04CEMJ',
'04CEMO',
'04CEMS',
'04CEMX',
'04CEMZ',
'04CEM1',
'04CEM3',
'04CEM4',
'04CEM7',
'04CEM8',
'04CEOC',
'04CEPD',
'04CEPM',
'04CEPO',
'04CEPR',
'04CEPS',
'04CEP2',
'04CERP',
'04CETE',
'04CET9',
'04CEUS',
'04CEX0',
'04CEX1',
'04CEX3',
'04CE19',
'04CE2P',
'04CE23',
'04CPEM',
'04EVEM',
'07CEM',
'07CEMC',
'07CEMO',
'07CEMS',
'07CEMZ',
'07CEM1',
'07CEM3',
'07CEM4',
'07CEM7',
'07CEM8',
'08CEM',
'08CEMC',
'08CEMJ',
'08CEMO',
'08CEMS',
'08CEMZ',
'08CEM1',
'08CEM3',
'08CEM4',
'08CEM7',
'08CEM8',
'09CEAG',
'09CEAP',
'09CEAS',
'09CEAT',
'09CEFE',
'09CEFG',
'09CEFO',
'09CEGF',
'09CEM',
'09CEMC',
'09CEMH',
'09CEMO',
'09CEMZ',
'09CEM1',
'09CEM3',
'09CEM4',
'09CEM7',
'09CEM8',
'09CEPD',
'09CEPM',
'09CEPO',
'09CEPR',
'09CEPS',
'09CEP2',
'09CERP',
'09CEX3',
'09CE2P',
'01CEMQ',
'04CEMQ',
'01CE50',
'04CE50',
'01PACE',
'04PACE',
'01TACE',
'04TACE',
'01CUE3',
'04CUE3',
'01CUE6',
'04CUE6',
'01CUE9',
'04CUE9',
'01CU12',
'04CU12',
'01CU23',
'04CU23',
'01CU26',
'04CU26',
'01CU29',
'04CU29',
'01CU22',
'04CU22',
'01CTL3',
'04CTL3',
'01CTL6',
'04CTL6',
'01CTL9',
'04CTL9',
'01CT12',
'04CT12',
'01CT23',
'04CT23',
'01CT26',
'04CT26',
'01CT29',
'04CT29',
'01CT22',
'04CT22',
'01FULL',
'04FULL') 
GROUP BY ASO_IDENTIFICACION;"))

r10 <- r10 %>% left_join(Pagos_Mora_1_CEM, by = c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))


r10 <- r10 %>% mutate(RECAUDO_VENCIDO_CEM = if_else(Edad_Inicial_CEM == 0 & Valor_Vencido_Periodo_CEM > 0,VALOR_RECAUDO_VENCIDO,RECAUDO_VENCIDO_CEM))

r10 <- r10 %>% select(-VALOR_RECAUDO_VENCIDO)

 # ----- SEGUROS ----

## VALORES INICIALES SEGUROS ## 

r10 <- r10 %>% left_join(Foto_inicial %>% select(ASO_IDENTIFICACION,Validacion_Seguros,Edad_Inicial_Seguros,Valor_Vencido_Periodo_Seguros,Total_Fac_Seguros), by = c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))


## VALORES HOY SEGUROS ##

r10 <- r10 %>% left_join(Seguros_hoy %>%  select(ASO_IDENTIFICACION,EDAD_CARTERA_HOY,VALOR_VENCIDO_HOY), by=c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))

r10 <- r10 %>% rename(EDAD_HOY_SEGUROS = EDAD_CARTERA_HOY)

r10 <- r10 %>% rename(VALOR_VENCIDO_SEGUROS_HOY = VALOR_VENCIDO_HOY)

r10 <- r10 %>% mutate(VALOR_VENCIDO_SEGUROS_HOY = if_else(is.na(VALOR_VENCIDO_CEM_HOY),0,VALOR_VENCIDO_CEM_HOY))


## PAGOS SEGUROS ## 

Pagos_Seguros <- dbGetQuery(Connecion_SQL,glue_sql("SELECT 
REC.ASO_IDENTIFICACION_ASOCIADO, 
SUM(REC.HRCD_VALOR_RECAUDO) AS VALOR_RECAUDO_TOTAL,
SUM(CASE 
      WHEN REC.HRCD_PERIODO_FACTURACION < 202506
      THEN REC.HRCD_VALOR_RECAUDO 
      ELSE 0 
      END) AS VALOR_RECAUDO_VENCIDO
      FROM GRC.GCC_HISTORIA_RECAUDO REC
      LEFT OUTER JOIN GRC.GCC_CONCEPTO CON ON REC.CON_CODIGO = CON.CON_CODIGO
      LEFT OUTER JOIN GRC.GCC_AGRUPACION_EMPRESA EMP ON CON.AGE_CODIGO = EMP.AGE_CODIGO
      WHERE 
      REC.HRCD_NRO_TRANSACCION NOT IN ('71','52','51')
      AND EMP.AGE_NOMBRE = 'COOMEVA'
      AND REC.HRCD_FECHA_RECAUDO BETWEEN TO_DATE('01/06/2025', 'DD/MM/YYYY') AND TO_DATE('30/06/2025', 'DD/MM/YYYY')
AND REC.CON_CODIGO IN('SEGAUTOC',
                                                                      'DESEMPLE',
                                                                      'PYMEBANC',
                                                                      'SEG ROTU',
                                                                      'SEGSOAT',
                                                                      'ASISTAFA',
                                                                      'VIDACOOM',
                                                                      'SEG AUTO',
                                                                      'HOGMASBA',
                                                                      'SEGINCBA',
                                                                      'INCCLIBA',
                                                                      'SEGAUTMD',
                                                                      'SEGAUTBO',
                                                                      'AUTOAMPB',
                                                                      'AUT PESA',
                                                                      'BOLBILLE',
                                                                      'CLINIMAS',
                                                                      'CLINIMA2',
                                                                      'SEG CUBR',
                                                                      'EVCRICOO',
                                                                      'EVCRIMP',
                                                                      'ECMPFTF',
                                                                      'FLE.HOG+',
                                                                      'SEG HOGA',
                                                                      'HOMEEJEC',
                                                                      'SEG INCE',
                                                                      'AUTLIV',
                                                                      'AUTLIB',
                                                                      'Seg+Prot',
                                                                      'SEG MOTO',
                                                                      'SEGMASCO',
                                                                      'SEGMOCHI',
                                                                      'PAGPROTN',
                                                                      'PAGO SEG',
                                                                      'PENPRVOL',
                                                                      'SEG PLAN',
                                                                      'VIDASOLI',
                                                                      'SEG.A.EJ',
                                                                      'SEG GAP',
                                                                      'AUTOLIV3',
                                                                      'PROT.EDU',
                                                                      'SEG PAGP',
                                                                      'PLAN100L',
                                                                      'SEGAUTOS',
                                                                      'SEGMYCAR',
                                                                      'MOVIBIC',
                                                                      'AUTOLICF',
                                                                      'AUTOLIVN',
                                                                      'LIVESECF',
                                                                      'LIVESEN',
                                                                      'MASPRONU',
                                                                      'VIDAEG',
                                                                      'VIDARENH',
                                                                      'VIDA',
                                                                      'LIVFULL',
                                                                      'LIVFULCF',
                                                                      'INCORIGI',
                                                                      'INCORICF',
                                                                      'RENTA HG',
                                                                      'RENTHONU',
                                                                      'SEG CIVI',
                                                                      'S.RC.Exc',
                                                                      'SEG RESC',
                                                                      'S.RC.CLI',
                                                                      'RCMEDLIV',
                                                                      'ORIVIVI',
                                                                      'RC MED',
                                                                      'ARCEPT',
                                                                      'ARCEBA',
                                                                      'RUNT',
                                                                      'SEGRUNT',
                                                                      'EQELECBA',
                                                                      'TAXIBANC',
                                                                      'SEG ACCI',
                                                                      'SEG ELEC',
                                                                      'SEG.SOAT',
                                                                      'SEG RENT',
                                                                      'SEG.VEH.',
                                                                      'SEGVICBA',
                                                                      'SEGVIGC',
                                                                      'SEGMOTBA',
                                                                      'SEGVEHBA',
                                                                      'SEGVEHCB',
                                                                      'VEHPESBA',
                                                                      'SEG SUST',
                                                                      'SEG PYME',
                                                                      'SEGMPSTO',
                                                                      'CREDASOC',
                                                                      'SEGVIDVA',
                                                                      'SEGVGFS',
                                                                      'SEG TAMP',
                                                                      'SEG.TAXI',
                                                                      'TOHOMLIF',
                                                                      'TOHOMLIV',
                                                                      'TMKBSEG',
                                                                      'VGORIGCF')
                                                   GROUP BY (REC.ASO_IDENTIFICACION_ASOCIADO)"))


r10 <- r10 %>% left_join(Pagos_Seguros %>%  select(ASO_IDENTIFICACION_ASOCIADO,VALOR_RECAUDO_TOTAL,VALOR_RECAUDO_VENCIDO), by=c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION_ASOCIADO"))

r10 <- r10 %>% rename(RECAUDO_TOTAL_SEGUROS = VALOR_RECAUDO_TOTAL)

r10 <- r10 %>% rename(RECAUDO_VENCIDO_SEGUROS = VALOR_RECAUDO_VENCIDO)

## Valor Recaudo Vencido Mora 1 ##

Pagos_Mora_1_SEGUROS <- dbGetQuery(Connecion_SQL,glue_sql("SELECT 
                                                   ASO_IDENTIFICACION,
                                                   SUM(HFR_VALOR_RCDO_VENC_FIN + HFR_VALOR_RCDO_VENC_MULT) AS VALOR_RECAUDO_VENCIDO
                                                   FROM GRC.GCC_HIST_FACT_RECAUDO
                                                   WHERE HFR_PERIODO_FACT = '202507'
                                                   AND CON_CODIGO IN ('SEGAUTOC',
                                                                      'DESEMPLE',
                                                                      'PYMEBANC',
                                                                      'SEG ROTU',
                                                                      'SEGSOAT',
                                                                      'ASISTAFA',
                                                                      'VIDACOOM',
                                                                      'SEG AUTO',
                                                                      'HOGMASBA',
                                                                      'SEGINCBA',
                                                                      'INCCLIBA',
                                                                      'SEGAUTMD',
                                                                      'SEGAUTBO',
                                                                      'AUTOAMPB',
                                                                      'AUT PESA',
                                                                      'BOLBILLE',
                                                                      'CLINIMAS',
                                                                      'CLINIMA2',
                                                                      'SEG CUBR',
                                                                      'EVCRICOO',
                                                                      'EVCRIMP',
                                                                      'ECMPFTF',
                                                                      'FLE.HOG+',
                                                                      'SEG HOGA',
                                                                      'HOMEEJEC',
                                                                      'SEG INCE',
                                                                      'AUTLIV',
                                                                      'AUTLIB',
                                                                      'Seg+Prot',
                                                                      'SEG MOTO',
                                                                      'SEGMASCO',
                                                                      'SEGMOCHI',
                                                                      'PAGPROTN',
                                                                      'PAGO SEG',
                                                                      'PENPRVOL',
                                                                      'SEG PLAN',
                                                                      'VIDASOLI',
                                                                      'SEG.A.EJ',
                                                                      'SEG GAP',
                                                                      'AUTOLIV3',
                                                                      'PROT.EDU',
                                                                      'SEG PAGP',
                                                                      'PLAN100L',
                                                                      'SEGAUTOS',
                                                                      'SEGMYCAR',
                                                                      'MOVIBIC',
                                                                      'AUTOLICF',
                                                                      'AUTOLIVN',
                                                                      'LIVESECF',
                                                                      'LIVESEN',
                                                                      'MASPRONU',
                                                                      'VIDAEG',
                                                                      'VIDARENH',
                                                                      'VIDA',
                                                                      'LIVFULL',
                                                                      'LIVFULCF',
                                                                      'INCORIGI',
                                                                      'INCORICF',
                                                                      'RENTA HG',
                                                                      'RENTHONU',
                                                                      'SEG CIVI',
                                                                      'S.RC.Exc',
                                                                      'SEG RESC',
                                                                      'S.RC.CLI',
                                                                      'RCMEDLIV',
                                                                      'ORIVIVI',
                                                                      'RC MED',
                                                                      'ARCEPT',
                                                                      'ARCEBA',
                                                                      'RUNT',
                                                                      'SEGRUNT',
                                                                      'EQELECBA',
                                                                      'TAXIBANC',
                                                                      'SEG ACCI',
                                                                      'SEG ELEC',
                                                                      'SEG.SOAT',
                                                                      'SEG RENT',
                                                                      'SEG.VEH.',
                                                                      'SEGVICBA',
                                                                      'SEGVIGC',
                                                                      'SEGMOTBA',
                                                                      'SEGVEHBA',
                                                                      'SEGVEHCB',
                                                                      'VEHPESBA',
                                                                      'SEG SUST',
                                                                      'SEG PYME',
                                                                      'SEGMPSTO',
                                                                      'CREDASOC',
                                                                      'SEGVIDVA',
                                                                      'SEGVGFS',
                                                                      'SEG TAMP',
                                                                      'SEG.TAXI',
                                                                      'TOHOMLIF',
                                                                      'TOHOMLIV',
                                                                      'TMKBSEG',
                                                                      'VGORIGCF')
                                                           GROUP BY (ASO_IDENTIFICACION);")) 

## Valor Recaudo Vencido Mora 1 ##

r10 <- r10 %>% left_join(Pagos_Mora_1_SEGUROS, by = c("CEDULA ASOCIADO" = "ASO_IDENTIFICACION"))


r10 <- r10 %>% mutate(RECAUDO_VENCIDO_SEGUROS = if_else(Edad_Inicial_Seguros == 0 & Valor_Vencido_Periodo_Seguros > 0,VALOR_RECAUDO_VENCIDO,RECAUDO_VENCIDO_SEGUROS))

r10 <- r10 %>% select(-VALOR_RECAUDO_VENCIDO)

## Homologación Actor de Gestión ##

r10 <- r10 %>% mutate(ACTOR_GESTION_HOMOLOGADO = case_when(SUBCAMPAÑA %in% c("CSSMORA1CORTE5","CSSMORA1CORTE10","CSSMORA1CORTE15","CSSMORA1CORTE20",
                                                               "CSSMORA1CORTE25","CSSMORA1CORTE30","CSS MORA 2","CSS MORA 3","CSS MORA 4",
                                                               "CSSCUOTA0HASTA6","REG BOGOTA","REG CALI","REG MEDELLIN","REG EJECAFETERO","REG PALMIRA","REG CARIBE") ~ "Moras Tempranas",
                                                                SUBCAMPAÑA == "BANCOOMEVA_U" ~ "Bancoomeva",
                                                     SUBCAMPAÑA %in% c(
                                                                        "MORA 1 CR",
                                                                        "MORA 2 - 5 CR",
                                                                        "MORA >= 150 CR",
                                                                        "PREVENTIVO CR",
                                                                        "CARTERA CASTIGO",
                                                                        "CR INSOLVENCIA",
                                                                        "JURIDICOS CR",
                                                                        "CLAUSULA CR",
                                                                        "CR EMPRESA") ~ "Creditos",
                                                     SUBCAMPAÑA %in% c("CSSALTAPRIORID", "CSSBAJAPRIORID") ~ "Inactivos",
                                             TRUE ~ SUBCAMPAÑA ))

## Arreglar Edades hoy ##

r10 <- r10 %>% mutate(EDAD_HOY_COOMEVA = if_else(Validacion_Coomeva == "SI" & is.na(EDAD_HOY_COOMEVA),0,EDAD_HOY_COOMEVA))

r10 <- r10 %>% mutate(EDAD_HOY_MP = if_else(Validacion_Mp == "SI" & is.na(EDAD_HOY_MP),0,EDAD_HOY_MP))

r10 <- r10 %>% mutate(EDAD_HOY_CEM = if_else(Validacion_CEM == "SI" & is.na(EDAD_HOY_CEM),0,EDAD_HOY_CEM))

r10 <- r10 %>% mutate(EDAD_HOY_SEGUROS = if_else(Validacion_Seguros == "SI" & is.na(EDAD_HOY_SEGUROS),0,EDAD_HOY_SEGUROS))


## ESTADOS DE CARTERA - CIERRE ##


r10 <- r10 %>%  mutate(ESTADO_CARTERA_COOMEVA = case_when(
  EDAD_HOY_COOMEVA == 0 ~ "NORMALIZA",
  EDAD_HOY_COOMEVA < Edad_Inicial_Coomeva ~ "MEJORA",
  EDAD_HOY_COOMEVA == Edad_Inicial_Coomeva ~ "MANTIENE",
  EDAD_HOY_COOMEVA > Edad_Inicial_Coomeva ~ "DETERIORA",
  TRUE ~ NA_character_
))


r10 <- r10 %>%  mutate(ESTADO_CARTERA_MP = case_when(
  EDAD_HOY_MP == 0 ~ "NORMALIZA",
  EDAD_HOY_MP < Edad_Inicial_MP ~ "MEJORA",
  EDAD_HOY_MP == Edad_Inicial_MP ~ "MANTIENE",
  EDAD_HOY_MP > Edad_Inicial_MP ~ "DETERIORA",
  TRUE ~ NA_character_
))


r10 <- r10 %>%  mutate(ESTADO_CARTERA_CEM = case_when(
  EDAD_HOY_CEM == 0 ~ "NORMALIZA",
  EDAD_HOY_CEM < Edad_Inicial_CEM ~ "MEJORA",
  EDAD_HOY_CEM == Edad_Inicial_CEM ~ "MANTIENE",
  EDAD_HOY_CEM > Edad_Inicial_CEM ~ "DETERIORA",
  TRUE ~ NA_character_
))


r10 <- r10 %>%  mutate(ESTADO_CARTERA_SEGUROS = case_when(
  EDAD_HOY_SEGUROS == 0 ~ "NORMALIZA",
  EDAD_HOY_SEGUROS < Edad_Inicial_Seguros ~ "MEJORA",
  EDAD_HOY_SEGUROS == Edad_Inicial_Seguros ~ "MANTIENE",
  EDAD_HOY_SEGUROS > Edad_Inicial_Seguros ~ "DETERIORA",
  TRUE ~ NA_character_
))


r10 <- r10 %>% distinct(`CEDULA ASOCIADO`, .keep_all = TRUE)

write_xlsx(r10, "C:/Users/jjvt9593/OneDrive - Grupo Coomeva/Escritorio/Carpetas/Corrección R-10/R10XEmpresas/Junio 2025.xlsx")
